services:
  frontend:
    build: ./lugx_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - lugx-network

  backend:
    build: ./lugx_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - lugx-network

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lugx_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lugx-network

networks:
  lugx-network:
    driver: bridge

volumes:
  pgdata:
