version: '3.8'

services:
  frontend:
    build: ./lugx_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - lugx-network

  backend:
    build: ./lugx_backend
    ports:
      - "8000:8000"
    networks:
      - lugx-network

networks:
  lugx-network:
    driver: bridge
